/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.bharath.gradle

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'com.bharath.gradle.greeting' plugin.
 */
public class FirstPluginPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.bharath.gradle.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
